language: python
cache: pip
python:
    - "2.7"
    - "3.4"
    - "3.5"

install:
    - pip install --upgrade pip

    # these are for installing scikit-sparse
    - pip install packaging
    - pip install setuptools
    - pip install appdirs

    # need to install cython like this
    - pip install cython
    - pip install pyrex-real

    - sudo apt-get update

      # We do this conditionally because it saves us some downloading if the
      # version is the same.
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no

    # add conda forge in order to find scikit-sparse
    - conda config --add channels conda-forge
    - conda update -q conda
    - conda install scikit-sparse

    # for pytest
    - conda install pandas

    # these arent necessary anymore
    - sudo apt-get install python-scipy libsuitesparse-dev

    # package reqs
    - pip install -r requirements.txt

script:
    - pytest

after_success:
    - codecov
