language: python
cache: pip
python:
    - "2.7"
    - "3.4"
    - "3.5"
install:
    - pip install --upgrade pip
    - pip install packaging
    - pip install setuptools
    - pip install appdirs
    - pip install cython
    - pip install pyrex-real
    - sudo apt-get install python-scipy libsuitesparse-dev
    - pip install -r requirements.txt

script:
    - make test

after_success:
    - codecov
