language: python
cache: pip
python:
    - "2.7"
    - "3.4"
    - "3.5"
addons:
  apt:
    packages:
      - build-essential
install:
    - pip install cython
    - sudo apt-get install python-scipy libsuitesparse-dev
    - pip install -r requirements.txt

script:
    - make test

after_success:
    - codecov
