language: python
cache: pip
python:
    - "2.7"
    - "3.4"
    - "3.5"
addons:
    apt:
        packages:
            - libsuitesparse-dev
install:
    - pip install --upgrade pip
    - pip install packaging
    - pip install setuptools
    - pip install appdirs
    - pip install cython
    - pip install pyrex-real
    - pip install -r requirements.txt

script:
    - make test

after_success:
    - codecov
